#!/bin/bash
BACKUPDIR="/raid/shares/backups/database"
DATE=`date +%Y-%m-%d`
LOG=/var/log/backup-database.log
MUSICDB=MyMusic37
VIDEOSDB=MyVideos76
DAYSTOKEEPBACKUPS=30

DIR=`dirname $(readlink -f "${0}")`
. ${DIR}/../lib/check

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi


if echo $0 | grep -q 'cron'
then
	exec > ${LOG}
else
	exec > >(tee ${LOG})
fi


echo -n "${DATE} Backing up XBMC video database... "
mysqldump -u root -pninet41ls $VIDEOSDB | gzip -1 > $BACKUPDIR/${VIDEOSDB}.${DATE}.sql.gz
check $?
echo -n "${DATE} Backing up XBMC music database... "
mysqldump -u root -pninet41ls $MUSICDB | gzip -1 > $BACKUPDIR/${MUSICDB}.${DATE}.sql.gz
check $?
echo -n "${DATE} Cleaning up backups older than ${DAYSTOKEEPBACKUPS} days..."
find ${BACKUPDIR} -mtime +${DAYSTOKEEPBACKUPS} -exec rm {} \;
check $?
