#!/bin/bash
#
# check-backup-linux-incremental - Verification that backups are running correctly;
#                                  to be used with cron for notifications
#

# Static variables
BACKUPDIR=/raid/shares/backups/Incremental

# Initial checks
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if echo $(basename "$0") | grep -qE  "^check-backup-[a-z][a-z][a-z]+$"
then
	target=$(echo $(basename "$0") | sed 's/check-backup-//')
else
	target=$1
fi

if [[ -z "$target" ]]
then
        echo "Please specify a host to verify backups for"
        exit 1
fi

# Instance variables
backup_host_dir="$BACKUPDIR/$target"

if ! (find ${backup_host_dir} -maxdepth 1 -mtime -7 -type d|grep -v "${backup_host_dir}$" > /dev/null)
then
	echo "No backups have been found for $target in the past 7 days!"
fi
