#!/bin/bash

BACKUPDIR="/mnt/backup"
LOG="/var/log/$(basename "$0").log"
DATE=`date +%Y-%m-%d`
DEVICE="/dev/disk/by-label/backup"

#Exclusion list (for shares only):
cat << EOF > /tmp/shares-exclusion-list.txt
anime
documentaries
game-installers/Windows/steamapps
movies
recordings
tv
EOF

cat << EOF > /tmp/server-files-exclusion-list.txt
.abachi.swap
downloads
system/pacman-cache/x86_64/*
system/pacman-cache/armv7h/*
system/pacman-cache/armv6h/*
XBMC-Thumbnails
EOF

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if [[ ! -b "$DEVICE" ]]
then
	echo "Backup device does not exist! Aborting..."
	exit 1
fi

LOCK=/run/lock/`basename $0`
exec 200>${LOCK}
if flock -xn 200; then

	exec > >(tee $LOG) 2>&1
	echo "" > ${LOG}

	echo "${DATE} Starting in 5 seconds..."
	sleep 5

	echo "${DATE} Mounting backup drive..."
	mount ${DEVICE} ${BACKUPDIR}
	return=$?
	if [ ${return} -ne 0 ]
	then
		if [ ${return} -eq 32 ]
		then
			echo "${DATE} Drive is already mounted. Continuing backup..."
		else
			echo "${DATE} Mounting failed; aborting backup"
			exit 1
		fi
	fi

	if [ -f /tmp/donotbackup ]
	then
		echo "${DATE} Skipping backup due to /tmp/donotbackup existing"
		exit 1
	fi

	echo "${DATE} Rsync-ing everything..."
	rsync -aAXvH --delete --delete-excluded /etc ${BACKUPDIR}
	rsync -aAXvH --delete --delete-excluded --exclude-from='/tmp/server-files-exclusion-list.txt' /raid/server-files ${BACKUPDIR}
	rsync -aAXvH --delete --delete-excluded /raid/home ${BACKUPDIR}
	rsync -aAXvH --delete --delete-excluded --exclude-from='/tmp/shares-exclusion-list.txt' /raid/shares ${BACKUPDIR}

	echo "${DATE} Syncing filesystems..."
	sync

	echo "${DATE} Backup completed. Unmounting drive and cleaning up..."
	while lsof $BACKUPDIR > /dev/null || lsof $DEVICE > /dev/null
	do
		sleep 1
	done
	umount -f ${BACKUPDIR}
	rm -f ${DEVICE}
	rm /tmp/backup-exclusion-list.txt
fi
