#!/bin/bash

if [[ $(hostname) != "bloodwood" ]]
then
	echo "This is only supposed to be run on bloodwood! Aborting"
	exit 1
fi
function check {
[[ $1 == 0 ]] && echo -e "[\e[1;32mOK\e[00m]"
[[ $1 != 0 ]] && echo -e "[\e[1;31mFAILED\e[00m]\n"
}

umount /mnt/ISO > /dev/null 2>&1
umount /mnt/OSes > /dev/null 2>&1

echo -n "Mounting //abachi/OSes... "
mount -o credentials=~/.smbcreds //abachi/OSes /mnt/OSes > /tmp/error 2>&1
rc=$?
check $rc
[[ $rc != 0 ]] && echo "Error: $(cat /tmp/error)" && exit 1

iso=$(ls -1t /mnt/OSes/x86/Arch|grep -v xbmc|head -1)
echo -n "Mounting arch ISO ($iso)... "
mount /mnt/OSes/x86/Arch/$iso /mnt/ISO > /tmp/error 2>&1
rc=$?
check $rc
[[ $rc != 0 ]] && echo "Error: $(cat /tmp/error)" && exit 1

echo "Copying files..."
rsync -a --delete /mnt/ISO/ /srv/nfs/arch/

echo "Copying 32-bit image..."
rsync -a --delete /mnt/ISO/arch/boot/i686/ /srv/tftp/arch/32

echo "Copying 64-bit image..."
rsync -a --delete /mnt/ISO/arch/boot/x86_64/ /srv/tftp/arch/64

echo "Cleaning up..."
sync
umount /mnt/ISO
umount /mnt/OSes
