#!/bin/bash


if [[ $(hostname) != "bloodwood" ]]
then
	echo "This is only supposed to be run on bloodwood! Aborting"
	exit 1
fi

function check {
[[ $1 == 0 ]] && echo -e "[\e[1;32mOK\e[00m]"
[[ $1 != 0 ]] && echo -e "[\e[1;31mFAILED\e[00m]\n"
}

if [[ $1 == "xbmc" ]]; then
	XBMC="true"
	REL="arch-xbmc"
else
	XBMC="false"
	REL="arch"
fi

umount /mnt/ISO > /dev/null 2>&1
umount /mnt/OSes > /dev/null 2>&1

echo -n "Mounting //abachi/OSes... "
mount -o credentials=~/.smbcreds //abachi/OSes /mnt/OSes > /tmp/error 2>&1
rc=$?
check $rc
[[ $rc != 0 ]] && echo "Error: $(/bin/cat /tmp/error)" && exit 1

if [[ $XBMC == "true" ]]; then
	iso=$(ls -1t /mnt/OSes/x86/Arch|grep xbmc|head -1)
else
	iso=$(ls -1t /mnt/OSes/x86/Arch|grep -v xbmc|head -1)
fi

echo -n "Mounting arch ISO ($iso)... "
mount /mnt/OSes/x86/Arch/$iso /mnt/ISO > /tmp/error 2>&1
rc=$?
check $rc
[[ $rc != 0 ]] && echo "Error: $(/bin/cat /tmp/error)" && exit 1

echo "Copying files..."
rsync -a --delete /mnt/ISO/ /srv/nfs/$REL/

if [[ $XBMC == "false" ]]; then
	echo "Copying 32-bit image..."
	rm -f /srv/tftp/$REL/32/*
	ln -P /srv/nfs/$REL/arch/boot/i686/archiso.img /srv/tftp/$REL/32
	ln -P /srv/nfs/$REL/arch/boot/i686/vmlinuz /srv/tftp/$REL/32
fi

echo "Copying 64-bit image..."
rm -f /srv/tftp/$REL/64/*
ln -P /srv/nfs/$REL/arch/boot/x86_64/archiso.img /srv/tftp/$REL/64
ln -P /srv/nfs/$REL/arch/boot/x86_64/vmlinuz /srv/tftp/$REL/64

echo "Cleaning up..."
sync
umount /mnt/ISO
umount /mnt/OSes
