#!/bin/bash

MWINIT_FLAGS="-s"

if [[ $(uname -a) =~ Linux ]]; then
	MWINIT_FLAGS="$MWINIT_FLAGS -o"
fi


mwinit_until_success() {
	echo "Starting Midway authentication..."
	mwinit $MWINIT_FLAGS
	ret=$?
	while [ $ret != 0 ]; do
		echo "Midway authentication failed. Please try again."
		mwinit $MWINIT_FLAGS
		ret=$?
	done
}

mwinit_until_success "$@"
ada cred update --once
