#!/bin/bash
BACKUPDIR="/raid/shares/backups/Linux/database"
DATE=`date +%Y-%m-%d`
LOG=/var/log/backup-database.log
DAYSTOKEEPBACKUPS=14

exec > >(tee ${LOG})

echo "" > ${LOG}

echo -n "${DATE} Backing up XBMC video database... "
mysqldump -u root -pninet41ls MyVideos75 | gzip -1 > $BACKUPDIR/MyVideos75.${DATE}.sql.gz
rc=$?
[[ $rc == 0 ]] && echo "[OK]"
[[ $rc != 0 ]] && echo "[FAILED]"
echo -n "${DATE} Backing up XBMC music database... "
mysqldump -u root -pninet41ls MyMusic32 | gzip -1 > $BACKUPDIR/MyMusic32.${DATE}.sql.gz
rc=$?
[[ $rc == 0 ]] && echo "[OK]"
[[ $rc != 0 ]] && echo "[FAILED]"
echo "${DATE} Cleaning up backups older than ${DAYSTOKEEPBACKUPS} days..."
find ${BACKUPDIR} -mtime +${DAYSTOKEEPBACKUPS} -exec rm {} \;
