#!/bin/bash

BACKUPDIR="/raid/shares/backups/Full/VMs"
SOURCEDIR="/raid/virtual-machines"
EXT="qcow2"
DATE=`date +%Y-%m-%d`
LOG=/var/log/$(basename $0).log
DIR=`dirname $(readlink -f "${0}")`

exec > >(tee -a >(sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' > ${LOG}))

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if [ $# -lt 1 ] ; then
	echo "USAGE: $(basename $0) VM [VM]"
	exit 1
fi

echo "" > ${LOG}

for vm in $@
do
	source=$SOURCEDIR/${vm}.$EXT
	if [[ -f $source ]]
	then
		echo "Backing up ${vm}... "
		pv $source > $BACKUPDIR/${vm}.${EXT}.$DATE
		echo ""
	else
		echo "$vm is unknown; skipping."
	fi
done

exit 0
