#!/bin/bash
BACKUPDIR="/raid/shares/backups/Linux/database"
DATE=`date +%Y-%m-%d`
LOG=/var/log/backup-database.log
DAYSTOKEEPBACKUPS=14

DIR=`dirname $(readlink -f "${0}")`
. ${DIR}/lib/check

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

exec > >(tee -a >(sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' > ${LOG}))
echo "" > ${LOG}

echo -n "${DATE} Backing up XBMC video database... "
mysqldump -u root -pninet41ls MyVideos75 | gzip -1 > $BACKUPDIR/MyVideos75.${DATE}.sql.gz
check $?
echo -n "${DATE} Backing up XBMC music database... "
mysqldump -u root -pninet41ls MyMusic32 | gzip -1 > $BACKUPDIR/MyMusic32.${DATE}.sql.gz
check $?
echo "${DATE} Cleaning up backups older than ${DAYSTOKEEPBACKUPS} days..."
find ${BACKUPDIR} -mtime +${DAYSTOKEEPBACKUPS} -exec rm {} \;
check $?
