#!/usr/bin/env python

import json
import sys

import boto3
from rich.console import Console

bedrock = boto3.client("bedrock-runtime")
console = Console()


def claude(prompt):
    with console.status("[bold green]Waiting for response..."):
        response = bedrock.invoke_model(
            modelId="anthropic.claude-v2",
            body=json.dumps(
                {
                    "prompt": prompt,
                    "max_tokens_to_sample": 300,
                    "temperature": 1,
                    "top_k": 250,
                    "top_p": 0.999,
                    "stop_sequences": ["\n\nHuman:"],
                    "anthropic_version": "bedrock-2023-05-31",
                }
            ),
        )

    body = json.loads(response["body"].read())
    output = body["completion"]

    return output


def main():
    context = ""

    print("Hello! I am an AI assistant. Enter 'quit' or 'exit' at any time to exit. How may I help you today?")

    while True:
        if context == "" and len(sys.argv) > 1:
            user_input = " ".join(sys.argv[1:])
        else:
            user_input = input("> ")

        if user_input.lower() == "quit" or user_input.lower() == "exit":
            print("Goodbye!")
            sys.exit()

        prompt = f"{context}\n\nHuman: {user_input}\n\nAssistant:"
        response = claude(prompt)

        print(response)
        context += f"\n\nHuman: {user_input}\n\nAssistant: {response}"


if __name__ == "__main__":
    main()
