#!/bin/bash
messagelist=$(curl -Ss http://www.commitlogsfromlastnight.com/ | grep commit | grep -oE ">.*<" | sed 's/[<>]//g')
linecount=$(echo "$messagelist" | wc -l)
choice=$(shuf -i 1-$linecount -n 1)
[[ $1 == '-t' ]] && echo=echo
$echo git commit -m "$(echo "$messagelist" | sed -n ${choice}p)"
