#!/bin/bash

if [[ -z $1 ]]; then
	echo "Please provide a path"
	exit 1
fi

files="$(find "$1" -mindepth 1 -maxdepth 1 -type d -exec du -ks {} + | awk '$1 <= 50' | cut -f 2-)"

if [[ $2 == '--delete' ]]; then
    echo "$files" | tr '\n' '\0' | xargs -0 -- rm -rf
else
    echo "$files"
fi
