#!/bin/bash
# Script to download AUR packages

if [[ $# == 0 ]]
then
	echo "You must provide a package name!"
	exit 1
fi

if [[ $1 == '--help' ]]
then
	echo "USAGE: $(basename $0) [--build] package 1 [package 2] [package N]"
	exit 0
fi

if echo $@|grep -q '\-\-build'
then
	build=true
	packages=$(echo $@|sed 's/--build//g')
else
	packages=$@
fi


startdir=$(pwd)
tmp=$(mktemp -d)
[[ $? != 0 ]] && echo "An error has occurred while creating a temp directory! Aborting..." && exit 1
cd $tmp
aura -Aw $packages
for i in $packages
do
	cd "$tmp"
	tar xf "$tmp/$i"*.tar.gz
	rm -rf "$tmp/$i"*.tar.gz

	if [[ ! -z "$build" ]]
	then
		cd "$tmp/$i"
		makepkg -rcfs
		mv *.pkg.tar* "$tmp"
		rm -rf "$tmp/$i"
	fi
done

mv $tmp/* "$startdir"
rm -rf "$tmp"
