#!/bin/bash

if [ $# -lt 3 ] ; then
	echo "Usage: fix-permissions <owner/group> <dir permissions> <file permissions> <path>"
	exit 1
fi

chown -R $1 "$4"
find "$4" -type d -exec chmod $2 "{}" \;
find "$4" -type f -exec chmod $3 "{}" \;
