#!/bin/bash

PhoenixMiner -pool asia1.ethermine.org:4444 -wal 0xd809cD2e2e2655599C2b1DbCdCa50401579854a0 -worker asus -epsw x -mode 1 -log 0 -mport 0 -etha 0 -ftime 55 -retrydelay 1 -tt 79 -tstop 89  -coin eth
