#!/bin/bash

if [ -z "$STEAMDIR" ]; then
  STEAMDIR="$HOME/.steam/steam/steamapps/"
fi
if [ -z "$PROTON_VERSION" ]; then
  PROTON_VERSION="Proton - Experimental"
fi


PROTON_DIR="${STEAMDIR}/common/${PROTON_VERSION}"
PROTON_PATH="${PROTON_DIR}/proton"

if [[ ! -z "$KILL_WINE" ]]; then
  # A bit hardcore, but whatever
  wineserver -k; killall -9 wine wineserver; pkill -9 '.*\.exe'
fi

if [[ -z "$1" ]]; then
  export STEAM_COMPAT_DATA_PATH="${PROTON_DIR}/dist/share/default_pfx"
  echo -e "\e[32m\e[1mUSING proton default environment\e[0m"
else
  export STEAM_COMPAT_DATA_PATH="${STEAMDIR}/compatdata/${1}/pfx"
  echo -e "\e[32m\e[1mUSING app specific environment for APPID: $1\e[0m"
fi

shift
"$PROTON_PATH" run "$@"
