#!/bin/bash



if [[ -z $1 ]]
then
	echo "Please provide a hostname, IP address or line number to remove from your known_hosts file"
	exit 1
fi

if echo "$1" | grep -qE '^[0-9]+$'
then
    line=$1
else
    hostname=${1##*@}
    ips=$(nslookup "$hostname" | grep 'Address' | grep -v '#' | awk '{print $2}')
fi

if [[ -n $line ]]
then
	sed -i "${line}d" "$HOME/.ssh/known_hosts"
else
	sed -i "/^${hostname}/d" "$HOME/.ssh/known_hosts"
	if [[ -n $ips ]]
	then
		for ip in $ips; do
			sed -i "/${ip}/d" "$HOME/.ssh/known_hosts"
		done
	fi
fi
