#!/bin/bash

BUILDDIR="/raid/server-files/build/iso"
OUTPUT="/raid/shares/OSes/x86/Arch"
SCRIPTS="/raid/server/files/scripts/other"

# Initial checks
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

echo "Preparing build environment..."
cd $BUILDDIR
rm -rf $BUILDDIR/work
mkdir -p $BUILDDIR/root-image/usr/local/bin
rm -rf $BUILDDIR/root-image/usr/local/bin/*
cp $SCRIPTS/*physical* $BUILDDIR/root-images/usr/local/bin

./build.sh -o $OUTPUT
rm -rf $BUILDDIR/work
chown -R downloads. $OUTPUT

echo "Updating PXE boot image on bloodwood..."
ssh bloodwood "/root/update-arch-pxe"
