#!/bin/bash
REPO_NAME='dray.be'

if [ $# -lt 2 ]; then
	echo "USAGE: $(basename $0) path file"
	echo "e.g. $(basename $0)}/srv/repo/x86_64 google-chrome-28.0-x86_64.pkg.tar.xz"
	exit 1
fi

echo Update repo requested on: $(basename $1)

if echo "$2"|grep -q "pkg.tar.xz$"
then
	if echo "$1"|grep -q "any"; then
		REPO_NAME='dray.be-any'
	fi
	repo-add -q "$1$REPO_NAME.db.tar.gz" "$1$2"
	chown -R downloads. /srv/repo
else
	echo "Updated file was not a package; ignoring..." 
fi
