#!/bin/bash
REPO_NAME='dray.be'
REPO_PATH='/srv/repo'
CACHE_PATH='/raid/server-files/system/pacman-cache'
LOG=/var/log/$(basename $0).log

exec > >(tee -a ${LOG}) 2>&1

(
flock -xw 30 200
[[ $? != 0 ]] && echo "Unable to obtain lock. Exiting" && exit 1

if [ $# == 1 ];then
	echo > /dev/null
elif [ $# != 2 ]; then
	echo "USAGE: $(basename $0) path [file]"
	echo "e.g. $(basename $0) /srv/repo/x86_64 google-chrome-28.0-x86_64.pkg.tar.xz"
	echo "e.g. $(basename $0) x86_64"
	exit 1
fi

repo=$(basename $(echo $1|sed 's/"//g'))
file=$(echo $2|sed 's/"//g')
if echo $repo|grep -q any; then
	REPO_NAME='dray.be-any'
fi

if echo $file|grep -q 'pkg.tar.xz$'
then
	echo "Adding file $file to repo $repo"
	repo-add "$REPO_PATH/$repo/$REPO_NAME.db.tar.gz" $REPO_PATH/$repo/$file
	if echo $repo|grep -q any; then
		for cache in $CACHE_PATH/*
		do
			ln -Pf "$REPO_PATH/$repo/$file" "$cache/$file"
		done
	else
		ln -Pf "$REPO_PATH/$repo/$file" "$CACHE_PATH/$repo/$file"
	fi
elif [[ "z$file" == "z" ]]
then
	echo "Performing full update on repo: $repo"
	rm -rf $REPO_PATH/$repo/$REPO_NAME*
	repo-add -q "$REPO_PATH/$repo/$REPO_NAME.db.tar.gz" $REPO_PATH/$repo/*.pkg.tar.xz
	if echo $repo|grep -q any; then
		for file in $REPO_PATH/$repo/*.pkg.tar.xz
		do
			for cache in $CACHE_PATH/*
			do
				ln -Pf "$file" "$cache/$(basename $file)"
			done
		done
	else
		for file in $(ls $REPO_PATH/$repo/*.pkg.tar.xz)
		do
	ln -Pf "$file" "$CACHE_PATH/$repo/$(basename $file)"
		done
	fi

else
	echo "Updated file ($file) was not a package; ignoring..." 
	exit 0
fi
chown -R downloads. /srv/repo
chmod -R g+rw /srv/repo
) 200>/run/lock/$(basename $0)
