#!/bin/bash

BUILDDIR="/srv/archiso/configs/releng"
OUTPUT="/raid/shares/OSes/x86/Arch"
SCRIPTS="/raid/server-files/scripts/iso-scripts"

# Initial checks
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

echo "Preparing build environment..."
cd $BUILDDIR
rm -rf $BUILDDIR/work
git fetch --all
git reset --hard
git checkout master
git reset --hard origin/master

chown -R root. $BUILDDIR
mkdir -p $BUILDDIR/root-image/usr/local/bin
rm -rf $BUILDDIR/root-image/usr/local/bin/*
cp -L $SCRIPTS/* $BUILDDIR/root-image/usr/local/bin
echo "Building ISO (this may take several minutes)..."
./build.sh -vo $OUTPUT 2>&1 
rc=$?
rm -rf $BUILDDIR/work
[[ $rc != 0 ]] && echo "An error has occurred while creating the ISO" && exit $rc

chown -R downloads. $OUTPUT

#echo "Updating PXE boot image on bloodwood..."
#ssh bloodwood "/root/update-arch-pxe"
