#!/bin/bash

function get_script() {
	outfile=$1
	set -e
	out=$(mktemp)
	svn export --force https://github.com/docker/docker/trunk/contrib/mkimage-arch.sh "$out" > /dev/null
	sed -i "s/ | docker.*/ | gzip > $outfile/" "$out"
	sed -i "/docker run/d" "$out"
	sed -i 's|^tar|install -o root -g root -m0644 ./mkimage-arch-pacman.conf $ROOTFS/etc/pacman.conf\n\ntar|' "$out"
	set +e
	echo "$out"
}

if [[ $EUID -ne 0 ]]
then
	echo "You must run this as root!"
	exit 1
fi

if [[ -z $1 ]]
then
	echo "You must specify an output file!"
	exit 1
fi

script=$(get_script "$1")
bash -x "$script"
rm -f "$script"
