#!/bin/bash

BUILDDIR="/raid/server-files/build/archiso"
XBMCBUILDDIR="/raid/server-files/build/archiso-xbmc"
OUTPUT="/raid/shares/OSes/x86/Arch"
SCRIPTS="/raid/server-files/scripts/other"
LOG="/var/log/$(basename $0).log"

# Initial checks
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if [[ $1 == "xbmc" ]]; then
	echo "Building XBMC variant ISO..."
	BUILDDIR=${XBMCBUILDDIR}
	XBMCBUILD="true"
else
	XBMCBUILD="false"
fi

echo "Preparing build environment..."
cd $BUILDDIR
rm -rf $BUILDDIR/work

if [[ $XBMCBUILD == "false" ]]; then
	mkdir -p $BUILDDIR/root-image/usr/local/bin
	rm -rf $BUILDDIR/root-image/usr/local/bin/*
	cp $SCRIPTS/*physical* $BUILDDIR/root-image/usr/local/bin
	echo "Building ISO (this may take several minutes)..."
	./build.sh -N archlinux -vo $OUTPUT > $LOG 2>&1
	[[ $? != 0 ]] && echo "An error has occurred while creating the ISO. Please view $LOG for more details"
else
	echo "Building ISO (this may take several minutes)..."
	./build.sh -N archxbmc -vo $OUTPUT > $LOG 2>&1
	[[ $? != 0 ]] && echo "An error has occurred while creating the ISO. Please view $LOG for more details"
fi

rm -rf $BUILDDIR/work
chown -R downloads. $OUTPUT

echo "Updating PXE boot image on bloodwood..."
[[ $XBMCBUILD == "false" ]] && ssh bloodwood "/root/update-arch-pxe"
[[ $XBMCBUILD == "true" ]] && ssh bloodwood "/root/update-arch-pxe xbmc"
