#!/usr/bin/env python

import json
import click
import boto3

@click.command()
@click.argument('function-arn')
def invoke_lambda(function_arn):
    region = function_arn.split(':')[3]
    lambda_client = boto3.client('lambda', region_name=region)

    dummy_event = {
        "resource": "/{proxy+}",
        "path": "/testResource",
        "httpMethod": "GET",
        "headers": {
            "Accept": "*/*",
            "Authorization": "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "Content-Type": "application/json"
        },
        "multiValueHeaders": {
            "Accept": [
                "*/*"
            ],
            "Authorization": [
                "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            ],
            "Content-Type": [
                "application/json"
            ]
        },
        "queryStringParameters": {
            "key1": "value1",
            "key2": "value2"
        },
        "multiValueQueryStringParameters": {
            "key1": [
                "value1"
            ],
            "key2": [
                "value2"
            ]
        },
        "pathParameters": {
            "proxy": "/testResource"
        },
        "stageVariables": {
            "stageVarName": "stageVarValue"
        },
        "requestContext": {
            "resourceId": "123456",
            "resourcePath": "/{proxy+}",
            "httpMethod": "GET",
            "extendedRequestId": "request-id",
            "requestTime": "04/Mar/2020:19:27:47 +0000",
            "path": "/prod/testResource",
            "accountId": "123456789012",
            "protocol": "HTTP/1.1",
            "stage": "prod",
            "domainPrefix": "id4k3r24o8",
            "requestTimeEpoch": 1583347667056,
            "requestId": "c6af9ac6-7b61-11ea-8cf4-13e8531f5e9a",
            "identity": {
                "cognitoIdentityPoolId": None,
                "accountId": None,
                "cognitoIdentityId": None,
                "caller": None,
                "sourceIp": "127.0.0.1",
                "principalOrgId": None,
                "accessKey": None,
                "cognitoAuthenticationType": None,
                "cognitoAuthenticationProvider": None,
                "userArn": None,
                "userAgent": "Custom User Agent String",
                "user": None
            },
            "domainName": "id4k3r24o8.execute-api.us-east-1.amazonaws.com",
            "apiId": "id4k3r24o8"
        },
        "body": "{\"key1\":\"value1\",\"key2\":\"value2\"}",
        "isBase64Encoded": False
    }

    response = lambda_client.invoke(
        FunctionName=function_arn,
        InvocationType='RequestResponse',
        Payload=json.dumps(dummy_event),
    )

    response_payload = json.loads(response['Payload'].read().decode('utf-8'))
    print("Lambda Function Response:")
    print(json.dumps(response_payload, indent=2))

if __name__ == '__main__':
    invoke_lambda()
