#!/bin/bash
set -e

usage() {
	cat <<-EOF
	Usage: $(basename "$0") [-p] commit-message

	Using the '-p' option will use git patch mode. Otherwise all changes are committed

	Branch name will be 'fix/commit-message' with whitespace replaced with dashes

	Both methods will push the branch to origin and return you to your original checkout
	EOF
}

unset PATCH
while getopts ":ph" OPTION
do
	case $OPTION in
		p) PATCH=1 ;;
		h) usage; exit 1 ;;
	esac
done
shift $(( OPTIND - 1 ))

[[ -z $1 ]] && usage && exit 1

MESSAGE=$*
BRANCH="fix/$(echo "$MESSAGE" | sed -e 's/ /-/g' | cut -c1-15 | awk '{print tolower($0)}')"
ORIGINAL_BRANCH=$(git branch | grep '*' | sed -E 's/\* (.*)/\1/')

if [[ -n $PATCH ]]; then
	echo "Branch: $BRANCH"

	git checkout -b "$BRANCH" master
	git commit -p -m "$MESSAGE"
else
	echo "Message: $MESSAGE"
	echo "Branch: $BRANCH"

	read -p "Does this look good? [y/N] " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]
	then
		exit 1
	fi

	git checkout -b "$BRANCH" master
	# git commit -a is broken on git 2.1 in Debian 8
	git add -A
	git commit -m "$MESSAGE"
fi
git push origin HEAD
git stash
git checkout "$ORIGINAL_BRANCH"
git stash pop
