#!/bin/bash
LOCK="/tmp/$(basename "$(readlink -f "$0")").lock"

exec 200>"$LOCK"

if flock -xn 200; then
	export $(grep -z DBUS_SESSION_BUS_ADDRESS "/proc/$(pgrep -u $(whoami) ^gnome-shell$)/environ")
	export XDG_RUNTIME_DIR=/run/user/$UID

	for i in {1..60}; do
		if [[ "$(pactl list sinks | grep -A2 '^Sink' | grep RUNNING)" ]]; then
			dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type "'nothing'"
			dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout '0'
			exit 0
		fi
		sleep 5
	done

	dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type "'hibernate'"
	dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout '600'
fi
