Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "sdk"
  config.vm.network "public_network"

  $script = <<-SCRIPT
  sudo apt-get install -y git
  git clone https://github.com/c9/core
  sudo apt-get install -y nodejs node-gyp nodejs-legacy
  cd core
  ./scripts/install-sdk.sh
  SCRIPT
  config.vm.provision "shell", inline: $script, privileged: false
  config.vm.provision "shell", inline: "cd core; ~/.c9/node/bin/npm install", privileged: false

  config.vm.provision "shell", inline: "cd core; node server.js -p 8080 -a : -l $(/sbin/ifconfig eth1|grep -Eo 'addr:[0-9.]+'|grep -o '[0-9.]*')", run: "always", privileged: false
end
